#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# lang.py

SETUP = {
    "choose_language": {"en": "Please choose your language:", "fr": "Veuillez choisir votre langue:"},
    "language_options": {"en": "[1] English\n[2] Français", "fr": "[1] Anglais\n[2] Français"},
    "invalid_choice": {"en": "Invalid choice. Defaulting to English.", "fr": "Choix invalide. Anglais sélectionné par défaut."},
    "moode_detect_fail": {"en": "❌ Unable to detect Moode version. Make sure you're running Moode >= 9.3.7.",
                          "fr": "❌ Impossible de détecter la version de Moode. Assurez-vous d'utiliser Moode ≥ 9.3.7."},
    "moode_too_old": {"en": "❌ Your version of Moode ({}) is too old. Minimum required is 9.3.7.",
                      "fr": "❌ Votre version de Moode ({}) est trop ancienne. La version minimale requise est 9.3.7."},
    "moode_ok": {"en": "✅ Moode version {} detected — OK.", "fr": "✅ Version de Moode {} détectée — OK."},
    "install_apt": {"en": "Checking system dependencies...", "fr": "Vérification des dépendances système..."},
    "apt_missing": {"en": "Installing missing dependencies: {}", "fr": "Installation des dépendances manquantes: {}"},
    "apt_ok": {"en": "✅ All APT dependencies are installed", "fr": "Toutes les dépendances APT sont installé"},
    "backup_created": {"en": "🔒 Backup created: {}", "fr": "🔒 Sauvegarde créée: {}"},
    "backup_exist": {"en": "🔒 Backup already exist: {}", "fr": "🔒 La Sauvegarde existe déjà: {}"},
    "repo_not_git": {"en": "⚠️ Folder {} exists but is not a Git repository. Update needed",
                           "fr": "⚠️ Le dossier {} existe mais n’est pas un dépôt Git. Mise à jour nécessaire"},
    "install_abort": {"en": "❌ Installation aborted (Ctrl+C).",
                      "fr": "❌ Installation interrompue (Ctrl+C)."},
    "already_uptodate": {"en": "✅ Already up-to-date (local {}, remote {}). Force Update? [Y/n]",
                         "fr": "✅ Déjà à jour (local {}, distant {}). Forcer la mise à jour? [O/n]"},
    "repo_backup_prompt": {"en": "⚠️ Folder {} already exists. Keep a backup before overwriting? [Y/n] ",
                           "fr": "⚠️ Le dossier {} existe déjà. Voulez-vous en conserver une copie avant d’écraser? [O/n] "},
    "repo_backup": {"en": "📦 Existing folder {} copied to {} before cloning.",
                    "fr": "📦 Le dossier existant {} a été copié en {} avant le clonage."},
    "checkout_tag": {"en": "📥 Checking out tag {} for {} ", "fr": "📥 Passage au tag {} pour {} "},
    "found_mergeable": {"en": "⚙️ Found mergeable files for {}: {}", 
                       "fr": "⚙️ Fichier mergeable trouvé pour {}: {}"},
    "found_force_dist": {"en": "⚙️ Major update → force new files for {}: {}", 
                       "fr": "⚙️ Mise à jour majeur → force nouveau fichier(s) pour {}: {}"},
    "cleaning_local": {"en": "⚡ Cleaning up {} (preserve: {})", "fr": "⚡ Nettoyage de {} (préservé: {})"},
    "moving_files": {"en": "📦 Moving cloned files from {} to {}",
                     "fr": "📦 Déplacement des fichiers clonés de {} vers {}"},
    "patch_skip_merge": {"en": "ℹ️ Patch update, no need to merge files.",
                         "fr": "ℹ️ Patch update, pas besoin de merger les fichiers."},
    "backup_file": {"en": "📦 Backed up {} → {}", "fr": "📦 Sauvegarde de {} → {}"},
    "forced_overwrite": {"en": "⚡ Forced overwrite of {} with {}", "fr": "⚡ Écrasement forcé de {} avec {}"},
    "merged_file": {"en": "📦 Merged {} with {}", "fr": "📦 Fusion de {} avec {}"},
    "no_dist": {"en": "ℹ️ No .dist file to merge/overwrite. ignored", "fr": "ℹ️ Aucun .dist à fusionner/écraser. Ignoré"},
    "clone_done": {"en": "✅ Done! {} deleted.", "fr": "✅ Terminé! {} supprimé."},
    "update_prompt": {"en": "✅  A newer release (local {}, remote {}) is available. Update now? [Y/n] ",
                      "fr": "✅  Une nouvelle version (local {}, distant {}) est disponible. Voulez-vous mettre à jour maintenant ? [O/n] "},
    "interactive_update_prompt": {"en": "⚙️ Do you want to update (U), force fresh reinstall (F), or skip (S)? [U/F/S] ",
                                  "fr": "⚙️ Voulez-vous mettre à jour (U), forcer la réinstallation complète (F) ou annuler (S) ? [U/F/S] "},
    "interactive_install_prompt": {"en": "⚙️ First install or Major update, Do you want to re/install (I) or abort (A)? [I/A] ",
                                   "fr": "⚙️ Première installation ou mise à jour majeure, voulez-vous ré/installer (I) ou annuler (A) ? [I/A] "},
    "interactive_abort": {"en": "❌ Operation aborted.", "fr": "❌ Opération annulée."},
    "update_done": {"en": "✅ Update completed successfully.", "fr": "✅ Mise à jour terminée avec succès."},
    "install_moode": {"en": "Checking for olipi-moode library...", "fr": "Vérification de la librairie olipi-moode..."},
    "moode_exists": {"en": "✅ olipi-moode already present at {}", "fr": "✅ olipi-moode déjà présent dans {}"},
    "moode_cloned": {"en": "✅ olipi-moode has been cloned to {}", "fr": "✅ olipi-moode a été cloné dans {}"},
    "install_core": {"en": "Checking for olipi_core library...", "fr": "Vérification de la librairie olipi_core..."},
    "core_exists": {"en": "✅ olipi_core already present at {}", "fr": "✅ olipi_core déjà présent dans {}"},
    "core_cloned": {"en": "✅ olipi_core has been cloned to {}", "fr": "✅ olipi_core a été cloné dans {}"},
    "i2c_check": {"en": "Checking I²C configuration...", "fr":"Vérification de la configuration I²C..."},
    "i2c_disabled": {"en": "⚠️  I²C is disabled. Would you like to enable it now? [Y/n]",
                     "fr": "⚠️  L'I²C est désactivé. Voulez-vous l'activer maintenant ? [O/n]"},
    "i2c_enabling": {"en": "Enabling I²C...", "fr": "Activation de l'I²C..."},
    "i2c_enabled": {"en": "✅ I²C is enabled.", "fr": "✅ L'I²C est activé."},
    "i2c_enable_failed": {"en": "❌ Failed to enable I²C. Please enable it manually with 'sudo raspi-config'.",
                         "fr": "❌ Échec de l'activation de l'I²C. Activez-la manuellement avec 'sudo raspi-config'."},
    "i2c_addresses_detected": {"en": "⇨ I²C addresses detected: {}", "fr": "⇨ Adresses I²C détectées: {}"},
    "i2c_display_ok": {"en": "ℹ️ OLED display detected on I²C bus {}. Check and confirm your choice in the list.", 
                       "fr": "ℹ️ Écran OLED détecté sur le bus I²C {}. Vérifiez et confirmez votre choix dans la liste."},
    "i2c_no_devices": {"en": "❌ No I²C devices detected. Check wiring and connections.",
                       "fr": "❌ Aucun périphérique I²C détecté. Vérifiez le câblage et les connexions."},
    "i2c_check_wiring": {"en": "❌ Check wiring or address jumpers on the OLED module.",
                         "fr": "❌ Vérifiez le câblage ou les cavaliers d'adresse sur le module OLED."},
    "i2c_no_dev_options": {"en": "[0] Back to screens / [s] Skip config / [x] Cancel install > ",
                           "fr": "[0] Revenir aux écrans / [s] Passer la config / [x] Annuler l'install > "},
    "i2c_choose_detected": {"en": "Select the I²C address to use for the display:", 
                            "fr": "Sélectionnez l’adresse I²C à utiliser pour l’écran:"},
    "i2c_choose_actions": {"en": "[0] Back to screens / [s] Skip config / [x] Cancel install",
                           "fr": "[0] Revenir aux écrans / [s] Passer la config / [x] Annuler l'install"},
    "i2c_saved": {"en": "✅ Address {} saved in config.ini", "fr": "✅ Adresse {} enregistrée dans config.ini"},
    "spi_check": {"en": "Checking SPI configuration...",
                  "fr": "Vérification de la configuration SPI..."},
    "spi_disabled": {"en": "⚠️ SPI is disabled. Would you like to enable it now? [Y/n]",
                     "fr": "⚠️ Le SPI est désactivé. Voulez-vous l'activer maintenant ? [O/n]"},
    "spi_enabling": {"en": "Enabling SPI...", "fr": "Activation du SPI..."},
    "spi_enabled": {"en": "✅ SPI is enabled.", "fr": "✅ Le SPI est activé."},
    "spi_enable_failed": {"en": "❌ Failed to enable SPI. Please enable it manually with 'sudo raspi-config'.",
                          "fr": "❌ Échec de l'activation du SPI. Activez-le manuellement avec 'sudo raspi-config'."},
    "spi_fb_detected": {"en": "⚡ SPI framebuffer detected:\n{}", "fr": "⚡ Framebuffer SPI détecté:\n{}"},
    "spi_devices_detected": {"en": "⚡ SPI device detected: {}", "fr": "⚡ Interfaces SPI détectées: {}"},
    "screen_discovery_fail": {"en": "❌ Could not import olipi_core.core_config; screen setup will be skipped.",
                              "fr": "❌ Impossible d'importer olipi_core.core_config ; configuration d'écran ignorée."},
    "screen_none_found": {"en": "No screen modules found.", "fr": "Aucun module d'écran trouvé."},
    "screen_choose_list": {"en": "Available screens:", "fr": "Écrans disponibles:"},
    "screen_choose_prompt": {"en": "Enter your screen number >", "fr": "Entrer le numéro de votre écran >"},
    "screen_skip_option": {"en": "[0] Skip screen configuration", "fr": "[0] Passer la configuration d'écran"},
    "screen_cancel_option": {"en": "[x] Cancel installation", "fr": "[x] Annuler l'installation"},
    "screen_skipped": {"en": "⏭ Screen configuration skipped.", "fr": "⏭ Configuration d'écran passée."},
    "screen_invalid_choice": {"en": "Invalid choice. Choose your screen by number.",
                              "fr": "Choix invalide. Choisissez votre écran par numéro."},
    "screen_selected": {"en": "Screen selected: {}", "fr": "Ecran sélectionné: {}"},
    "screen_save_fail": {"en": "❌ Failed to save screen to config.ini", "fr": "❌ Échec de l'enregistrement dans config.ini"},
    "screen_spi_info": {"en": "SPI screen selected — Enter GPIO (BCM) pin numbers. Type the value and press Enter.",
                        "fr": "Écran SPI sélectionné — Renseignez les numéros de broches GPIO (BCM). Tapez la valeur puis appuyez sur Entrée."},
    "screen_dc_prompt": {"en": "DC pin, ex. 23 >", "fr": "Broche DC, ex. 23 >"},
    "screen_reset_prompt": {"en": "RESET pin, ex. 24 >", "fr": "Broche RESET, ex. 24 >"},
    "screen_bl_prompt": {"en": "BL pin (backlight) — Only if present: you can use any free gpio or leave empty and connect it to 3.3v >",
                         "fr": "Broche BL (backlight) — Seulement si présent: Utiliser un GPIO libre ou laisser vide et branchez-la sur 3.3v >"},
    "screen_saved_ok": {"en": "Screen configuration saved. You need to reboot at end of installation", 
                        "fr": "Configuration de l'écran enregistrée. Vous devrez redémarrer le Raspberry à la fin de l'installation"},
    "low_ram_warning": {"en": "\n⚠️ This device has {}MB RAM. Enable ZRAM for better stability.",
                        "fr": "\n⚠️ Ce périphérique a {}Mo de RAM. Activez ZRAM pour plus de stabilité."},
    "zram_prompt": {"en": "Would you like to enable ZRAM ({}MB, lz4) and disable the default swap? [Y/n]",
                    "fr": "Voulez-vous activer ZRAM ({}Mo, lz4) et désactiver le swap par défaut ? [O/n]"},
    "zram_installing": {"en": "Installing zram-tools...", "fr": "Installation de zram-tools..."},
    "zram_not_present": {"en": "ZRAM device not present.", "fr": "Aucun device ZRAM détecté."},
    "disable_swap_prompt": {"en": "Swap on disk detected: {}. Disable it and replace with ZRAM? [Y/n]",
                            "fr": "Swap sur disque détecté: {}. Le désactiver et le remplacer par ZRAM ? [O/n]"},
    "confirm_remove_swapfile": {"en": "Remove swap file {}? [Y/n]", "fr": "Supprimer le fichier de swap {} ? [O/n]"},
    "zram_and_swap_warning": {"en": "ZRAM active but classic swap still enabled: {}.",
                              "fr": "ZRAM actif mais swap classique encore activé: {}."},
    "reconfigure_zram_prompt": {"en": "Reconfigure ZRAM with recommended settings? [Y/n]",
                                "fr": "Reconfigurer ZRAM avec les paramètres recommandés ? [O/n]"},
    "zram_backup": {"en": "🔒 Backup of zramswap created: {}",
                    "fr": "🔒 Sauvegarde de zramswap créée: {}"},
    "zram_nobackup": {"en": "🔒 Backup of zramswap already exist: {}",
                      "fr": "🔒 Sauvegarde de zramswap existe déjà: {}"},
    "disable_swap_done": {"en": "Classic swap disabled.", "fr": "Swap classique désactivé."},
    "removed_swapfile": {"en": "Removed swap file {}", "fr": "Fichier de swap supprimé: {}"},
    "zram_installation_aborted": {"en": "ZRAM installation aborted by user.",
                                  "fr": "Installation de ZRAM annulée par l'utilisateur."},
    "zram_done": {"en": "✅ ZRAM has been configured.", "fr": "✅ ZRAM a été configuré."},
    "zram_failed": {"en": "❌ Failed to configure ZRAM.", "fr": "❌ Échec de la configuration de ZRAM."},
    "venv_found": {"en": "\nVirtual environment found at {}.", "fr": "\nEnvironnement virtuel trouvé à {}."},
    "venv_reuse_choice": {"en": "\n[1] Reuse and update\n[2] Delete and recreate\n[3] Skip",
                          "fr": "\n[1] Réutiliser et mettre à jour\n[2] Supprimer et recréer\n[3] Passer"},
    "venv_reuse_update": {"en": "🔄 Reusing existing virtual environment at {} — updating dependencies...",
                          "fr": "🔄 Réutilisation de l'environnement virtuel à {} — mise à jour des dépendances..."},
    "venv_delete": {"en": "🗑 Deleting existing virtual environment...",
                    "fr": "🗑 Suppression de l'environnement virtuel existant..."},
    "venv_skipped": {"en": "⏭ Virtual environment configuration skipped.", "fr": "⏭ Configuration de l'environnement virtuel passée."},
    "venv_install": {"en": "⇨ Create a dedicated venv in {}",
                         "fr": "⇨ Création du venv dédié dans {}"},
    "install_requirement": {"en": "Installing Python dependencies...", "fr": "Installation des dépendances Python..."},
    "user_detected": {"en": "\n⇨ Detected user: {}", "fr": "\n⇨ Utilisateur détecté: {}"},
    "prompt_invalid": {"en": "Invalid choice.", "fr": "Choix invalide."},
    "install_services": {"en": "⇨ Installing required services...","fr": "⇨ Installation des services requis..."},
    "service_menu": {"en": "Service {}:\n[1] Install\n[2] View content\n[3] Skip",
                     "fr": "Service {}:\n[1] Installer\n[2] Afficher le contenu\n[3] Passer"},
    "service_view_header": {"en": "----- {}.service -----", "fr": "----- {}.service -----"},
    "service_created": {"en": "✅ Service {} created successfully.", "fr": "✅ Service {} créé avec succès."},
    "service_enabled": {"en": "✅ Service {} enabled.", "fr": "✅ Service {} activé."},
    "service_skipped": {"en": "⚠️  Service {} installation cancelled.", "fr": "⚠️  Installation du service {} annulée."},
    "permission_denied": {"en": "❌ Permission denied. Please run this script with sudo.",
                          "fr": "❌ Permission refusée. Veuillez exécuter ce script avec sudo."},
    "profile_update": {"en": "\n⇨ Updating ~/.profile with useful olipi-moode commands...",
                       "fr": "\n⇨ Mise à jour de ~/.profile avec les commandes utiles pour olipi-moode..."},
    "profile_updated": {"en": "✅ ~/.profile updated successfully.", "fr": "✅ ~/.profile mis à jour avec succès."},
    "profile_update_error": {"en": "❌ Failed to update ~/.profile: {}", "fr": "❌ Échec de la mise à jour de ~/.profile: {}"},
    "install_done": {"en": "\n✅ Installation complete.", "fr": "\n✅ Installation terminée."},
    "controle_explanation": {"en": "\n⚙️ Controle configuration:"
                                   "\n- GPIO buttons or rotary: configure pins in config.ini"
                                   "\n- IR Remote: Run ' python3 {} ' to install and configure LIRC.",
                             "fr": "\n⚙️ Configuration des Controle:"
                                   "\n- Boutons GPIO ou encodeur rotatif: configurez les broches dans config.ini."
                                   "\n- Télécommande IR: Executez ' python3 {} ' pour installer et configurer LIRC."},
    "moode_reminder": {"en": "\n⚠️  Reminder: To display the Spectro, activate Loopback in Moode (configure > audio > ALSA Options)\nand change show_spectrum = false to true in ~/olipi-moode/config.ini\n\n",
                       "fr": "\n⚠️  Rappel: Pour afficher le Spectro, activer Loopback dans Moode (configure > audio > ALSA Options)\net changer show_spectrum = false à true dans ~/olipi-moode/config.ini\n"},
    "develop_done": {"en": "✅ Development mode setup complete.",
                     "fr": "✅ La branche de développement a été installée avec succès."},
    "reboot_prompt": {"en": "\n⇨ Do you want to reboot now? [Y/n] > ", "fr": "\n⇨ Voulez-vous redémarrer maintenant ? [O/n] > "},
    "reboot_cancelled": {"en": "⚠️  Reboot cancelled. Please reboot manually later.",
                         "fr": "⚠️  Redémarrage annulé. Veuillez redémarrer manuellement plus tard."}
}
